-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- This is the base locale; values can be "true" so they default to their key, or any string to override that behaviour.
local L = LibStub("AceLocale-3.0"):NewLocale("SexyReputation", "enUS", true)


L["Active Factions Only"] = true
L["Alt-Click:"] = true
L["Bar"] = true
L["Both Standing and Reputation"] = true
L["Changes"] = true
L["Click:"] = true
L["Color Text"] = true
L["Color standing and reputation fields based on your standing with the different factions."] = true
L["Configure the LDB display of the tracked faction."] = true
L["Configure the look and feel of the faction tooltip."] = true
L["Faction"] = true
L["Factions"] = true
L["Fold / unfold faction headers."] = true
L["Last Month"] = true
L["Last Week"] = true
L["No changes recorded in the last 30 days."] = true
L["None"] = true
L["Only show factions with recent reputation changes."] = true
L["Percentage"] = true
L["Recent reputation changes"] = true
L["Reputation"] = true
L["Reputation Only"] = true
L["Session"] = true
L["Sexy Reputation"] = true
L["Sexy Reputations"] = true
L["Show Gains"] = true
L["Show Name"] = true
L["Show Percentage"] = true
L["Show reputation gained or lost in the session and today."] = true
L["Show the name of the tracked faction."] = true
L["Show the reputation numbers for the tracked faction."] = true
L["Show the reputation percentage in the current standing level for the tracked faction."] = true
L["Show the session changes for the tracked faction."] = true
L["Show the standing of the tracked faction."] = true
L["Show your rep as a percentage of the reputation standing (i.e Neutral 1500/3000 = 50%)"] = true
L["Standing"] = true
L["Standing Colors"] = true
L["Standing Only"] = true
L["Standing Style"] = true
L["Text"] = true
L["Text Display"] = true
L["Text Reputation Style"] = true
L["The colors used for the bar/text for the reputation standings."] = true
L["This faction is currently being tracked."] = true
L["Today"] = true
L["Toggle faction tracking state on and off."] = true
L["Tooltip Options"] = true
L["Using the faction tooltip:"] = true
L["Whether to show the reputation level as a bar, text or not at all"] = true
L["Whether to show the standing and/or reputation level text."] = true
L["Yesterday"] = true
