-- Generated by Babelfish script, do not add strings manually, only translate existing strings.
-- This is the base locale; values can be "true" so they default to their key, or any string to override that behaviour.
local L = LibStub("AceLocale-3.0"):NewLocale("SexyReputation", "enUS", true)


L["Change"] = true
L["Color fields based on your standing with the different factions."] = true
L["Faction"] = true
L["Factions"] = true
L["Only show factions that have had reputation changes in the past 30 days."] = true
L["Reputation"] = true
L["Session"] = true
L["Sexy Reputations"] = true
L["Show Changes Only"] = true
L["Show Gains"] = true
L["Show Percentage"] = true
L["Show Reputation"] = true
L["Show Standing"] = true
L["Show reputation gained or lost in the session and today."] = true
L["Show reputation values, ie 4543 / 12000."] = true
L["Show the faction standing text, i.e Hated, Neutral etc."] = true
L["Show your rep as a percentage of the reputation standing (i.e Neutral 1500/3000 = 50%)"] = true
L["Standing"] = true
L["Standing Color"] = true
L["Today"] = true
